### ISSUE TITLE
Python 3.6.9 support?

### ISSUE THREAD

**Issue by hdr110** [hhtznr/pyvideothumbnailer#1]
Hi. I've been trying to use your code in google colab to manage file G-drive videos. but unfortunately, colab is running python 3.6.9, and the "__future__" module is not defined in this version. Is there any chance I can use your code there?

**Comment by hhtznr** [comment]
The future module is only needed for the annotations regarding the types of the function parameters and the return types of the functions, which eases understanding the code, but is not necessary to run it. So, if you delete these annotations, you should also be able to delete the import of the future module.

**Comment by hdr110** [comment]
Thanks for your answer. I've already deleted the future module but It keeps getting this error:


`Traceback (most recent call last):
  File "pyvideothumbnailer.py", line 63, in <module>
    class PyVideoThumbnailerParameters:
  File "pyvideothumbnailer.py", line 137, in PyVideoThumbnailerParameters
    def from_defaults() -> PyVideoThumbnailerParameters.PyVideoThumbnailerParameters:
NameError: name 'PyVideoThumbnailerParameters' is not defined`


I should say that I'm not an expert using Python and so I might be doing something wrong somewhere. (I even changed some parts on functions but still nothing)
Can you fix this for me so I can use it?

**Comment by hdr110** [comment]
Thanks. I got it solved by removing annotations. Here's something else I don't know what to do about it. when I choose to scan subdirectories with the --recursive [path of files] command, I get this error,
`Traceback (most recent call last):
  File "pyvideothumbnailer.py", line 786, in <module>
    process_file_or_directory(params)
  File "pyvideothumbnailer.py", line 536, in process_file_or_directory
    process_file_or_directory(file_path, True)
TypeError: process_file_or_directory() takes 1 positional argument but 2 were given`

Is this also related to the future module or it's about something else?
I gotta tell you I'm not a Python expert :) Yet!

**Comment by hhtznr** [comment]
Support of Python <= 3.7 is not planned to be enabled.
