### ISSUE TITLE
How to remove the image metadata display

### ISSUE THREAD

**Issue by botzill** [hhtznr/pyvideothumbnailer#11]
Hi.

Is it possible to remove the generated text with metadata on the image?

**Comment by hhtznr** [comment]
There was no option to do so. But have a look at the new [release 1.2.0](https://github.com/hhtznr/pyvideothumbnailer/releases/tag/v1.2.0). You have a new argument `--no-header` and a corresponding config file option `no_header` to prevent the header from being added.

Please provide feedback if this is what you were looking for and if it works as expected.

**Comment by botzill** [comment]
Yes @hhtznr, exactly what I need, works great!

Thanks a lot.

**Comment by hhtznr** [comment]
You're welcome. Have fun!
