### ISSUE TITLE
Create a package so that we can install using pip

### ISSUE THREAD

**Issue by botzill** [hhtznr/pyvideothumbnailer#12]
Would be really good to create a package out of it and we can easily install via pip.

Thanks.

**Comment by hhtznr** [comment]
I restructured and adapted the source, so it will build as Python package on  [PyPI](https://pypi.org/project/pyvideothumbnailer/).

 As of [Release 2.0.1](https://github.com/hhtznr/pyvideothumbnailer/releases/tag/v2.0.1), you can install via

```
pip install pyvideothumbnailer
```

**Comment by botzill** [comment]
Nice @hhtznr! Thanks a lot
