### ISSUE TITLE
missing option for additional info  on the thumbnail like creator, freetext and so far

### ISSUE THREAD

**Issue by Bootsektor** [hhtznr/pyvideothumbnailer#4]
60d59
<
65a65,68
> # added for remark
> remark="software used https://github.com/hhtznr/pyvideothumbnailer"
> DEFAULT_REMARK = remark
>
73c76
<                  raise_errors: bool, verbose: bool):
---
>                  raise_errors: bool, verbose: bool, remark: str):
137a141,142
>         self.remark = remark
>
163c168,169
<                                             DEFAULT_VERBOSE)
---
>                                             DEFAULT_VERBOSE,
>                                             DEFAULT_REMARK)
197c203
<     minutes = int((duration - hours * 60) / 60)
---
>     minutes = int((duration - (hours * 3600)) / 60)
371c377
<
---
>     remark_info ='Info : {}'.format(params.remark)
376a383
>         print(remark_info)
396c403
<
---
>     text_height_remark_info = header_font.getsize(remark_info)[1]
405a413,416
>     header_height += text_line_spacing
>     header_height += text_height_remark_info
>     header_height += text_line_spacing
>
435a447,449
>     y += text_height_remark_info
>     y += text_line_spacing
>     thumbnails_draw.text((x, y), remark_info, params.header_font_color, font=header_font)
632a647,649
>     parser.add_argument('--remark',
>                         type=str,
>                         help='The remark about the creator of the file')
651d667
<
767c783,784
<
---
>     if args.remark is not None:
>         params.remark = args.remark
773c790
<
---
>     print(params.remark)

**Comment by hhtznr** [comment]
Placing of an optional comment at the bottom of the header was added with commit b9f25ca55cdb7a342df75a278d30f624d4c7d549.
