### ISSUE TITLE
recursive params seems not working

### ISSUE THREAD

**Issue by silicon14** [hhtznr/pyvideothumbnailer#6]
hello,
in line 606, global params is updated every time before recursion in line 609.
so it only works for the first sub-dir in the path, and will simply skip the rest of files.

**Comment by hhtznr** [comment]
Thank you for reporting this bug. It was fixed with commit [18a55dc](https://github.com/hhtznr/pyvideothumbnailer/commit/18a55dc0184c487716603d917a099db941ddd676). Bug fix release [1.1.1](https://github.com/hhtznr/pyvideothumbnailer/releases/tag/v1.1.1) is now available.
