### ISSUE TITLE
Problem with the photo, header too large

### ISSUE THREAD

**Issue by BrayanTF** [hhtznr/pyvideothumbnailer#8]
I don't know what the reason is, but now every time I use the script it creates some images with a header with a lot of height, I have downloaded the code again but the same thing keeps happening to me. As I have indicated I have returned to the code and it is still happening, the .conf I have not changed.
I attach the images in imgur

https://imgur.com/a/6NF6e8k

Commands to used:

python C:\pyvideothumbnailer\pyvideo.py  '.\Sin salida M1080.atomixhq.link.mkv'

python C:\pyvideothumbnailer\pyvideo.py  --background-color black --header-font-color white --columns 5 --rows 4 '.\Sin salida M1080.atomixhq.link.mkv'

 python3 C:\pyvideothumbnailer\pyvideo.py  --background-color black --header-font-color white --width 1680 --columns 5 --rows 4 '.\Sin salida M1080.atomixhq.link.mkv'

I used Window 11

**Comment by hhtznr** [comment]
Thank you for reporting this bug. I apologize for the inconvenience.

I think, I accidentally introduced this bug with commit 10d1286ef798e453945616e6c49c1f44c4a1ad33. I replaced a now deprecated method from PIL and misunderstood proper usage of the replacement. It seems to me that I somehow used the previous version 1.1.1 of pyvideothumbnailer when testing it as everything looked fine to me.

Please have a look at the new release [pyvideothumbnailer 1.1.3](https://github.com/hhtznr/pyvideothumbnailer/releases/tag/v1.1.3l) and provide feedback if everything is to your expectations.

**Comment by BrayanTF** [comment]
Thank you very much, yes version 1.1.13 works perfectly for me. Thank you for solving it and more being these dates.

**Comment by hhtznr** [comment]
Thank you for the immediate feedback. Good to have confirmation that it works again as it is supposed to work.
